low_voltage_threshold: 3.3
low_voltage_hysteresis: 0.2

camera_topic_name: "~cv_camera/image_raw"

robohead_controller_actions_match: { # сопоставление голововой команды из voice_recognizer_pocketsphinx/gram.txt и файла, запускаемого на исполнение
  "wait_action" : "turtlebot_controller_actions.std_wait.action",
  "low_bat_action" : "turtlebot_controller_actions.std_low_bat.action",
  "слушайробот" : "turtlebot_controller_actions.std_attention.action",
  "покажи левое ухо": "turtlebot_controller_actions.std_left_ear.action",
  "покажи правое ухо": "turtlebot_controller_actions.std_right_ear.action",
  "покажи уши" : "turtlebot_controller_actions.std_ears.action",
  "сделай фото": "turtlebot_controller_actions.std_make_photo.action",
  "поздоровайся": "turtlebot_controller_actions.std_greeting.action",
  "повернись вправо": "turtlebot_controller_actions.std_turn_right.action",
  "повернись влево": "turtlebot_controller_actions.std_turn_left.action",
  "езжай сюда": "turtlebot_controller_actions.std_move_here.action",
  "езжай отсюда": "turtlebot_controller_actions.std_move_away.action",
}

turtlebot_topic_cmd_vel_name: "/cmd_vel"
turtlebot_topic_odom_pose2d_name: "/odom_pose2d"